#1 - Deploy manifest to a test Kubernetes cluster. The service should expose nginx, but it currently doesn't work. Fix the issue so that you can forward the service and access the webpage. Send the commands you used to debug, the change you did, and a curl proving it works. 
 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: web 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: website 
  template: 
    metadata: 
      labels: 
        app: website 
    spec: 
      containers: 
      - name: nginx 
        image: nginx:latest 
        ports: 
        - containerPort: 80 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: web 
spec: 
  type: ClusterIP 
  selector: 
    app: website # fixed the label and selector 
  ports: 
    - port: 80 
      targetPort: 80 
 
